name: CoverAlls Tests

on:
  push:
    branches: [v5-update]
  pull_request:
    branches: [v5]

jobs:
  test-and-coveralls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 25

      # Loop through each package and run tests sequentially
      - name: Run tests for all packages sequentially
        run: |
          for pkg in core jsx css babel-plugin; do
            echo "== Testing $pkg =="
            cd $pkg
            export COVERALLS_FLAG_NAME=$pkg
            npm i
            npm run build
            npm run test-coverage
            cd ..
          done

      - name: Coveralls
        uses: coverallsapp/github-action@v2
