@startuml
title Vasille.js core architecture

Destroyable <|-- IValue
Destroyable <|--- VasilleNode

IValue <|-- Reference
IValue <|-- Pointer
IValue <|--- Binding
IValue <|-- Expression
Binding <|-- AttributeBinding
Binding <|-- StyleBinding
Binding <|-- ClassBinding

VasilleNode <|-- BaseNode
VasilleNode <|-- TextNode

BaseNode <|-- ExtensionNode
BaseNode <|-- AppNode
BaseNode <|-- TagNode

ExtensionNode <|-- SwitchNode
ExtensionNode <|-- RepeatNode
ExtensionNode <|-- RepeatNodeItem

RepeatNode <|-- BaseView
RepeatNode <|-- Repeater

BaseView <|-- ArrayView
BaseView <|-- ObjectView
BaseView <|-- MapView
BaseView <|-- SetView

@enduml
