@startuml
!include uml-style.iuml

Reactive <|-- Fragment
Fragment <|-- TextNode
Fragment <|-- INode
Fragment <|-- DebugNode
Fragment <|-- Watch
Fragment <|-- RepeatNode

INode <|-- Extension
INode <|-- AppNode
INode <|-- Tag

Extension <|-- Component

RepeatNode <|-- BaseView

BaseView <|-- ArrayView
BaseView <|-- ObjectView
BaseView <|-- MapView
BaseView <|-- SetView

AppNode <|-- App

@enduml
